name: updateBirdNerdSelection

on:
  schedule:
    - cron: '1 4 * * *' # 12:01 am eastern time
  workflow_dispatch: # manual triggering 

jobs:
  run-birdnerd-script:
    runs-on: ubuntu-latest
    steps:
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install R Packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::ebird

      - name: Checkout Git Repository where Script Lives
        uses: actions/checkout@v3

      - name: Run R Script
        run: Rscript ./selectionPicker.R

      - name: Commit New CSVs to Repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add BirdSightingLists/level1Sightings.csv
          git add BirdSightingLists/level2Sightings.csv
          git add BirdSightingLists/level3Sightings.csv
          git add BirdSightingLists/level4Sightings.csv
          git add BirdSightingLists/level5Sightings.csv
          git commit -m 'New Bird Selection CSVs'
          git push
